# src/main/resources/application-dev.yml (разработка)

spring:
#  datasource:
#    # 🟢 ИСПРАВЛЕНО: Теперь dev-режим смотрит на правильный выделенный порт платформы и общую базу
#    url: jdbc:postgresql://localhost:5433/logistics_platform_db?currentSchema=cargo_schema
#    username: ${DB_USERNAME:postgres}
#    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update # На деве разрешаем Hibernate обновлять схему на лету

logging:
  level:
    com.innowise.logistics.cargoservice: DEBUG
