# src/main/resources/application.yml для cargo-service

server:
  port: 8085

spring:
  application:
    name: be-logistics-platform-cargo-service

  # DataSource для PostgreSQL (основная БД)
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=cargo_schema
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jackson:
    serialization: # чтобы Jackson правильно сериализует/десериализует.
      write-dates-as-timestamps: false
    time-zone: UTC

  # JPA / Hibernate
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
        default_schema: cargo_schema
    open-in-view: false

  liquibase:
    enabled: true
#    enabled: false   # временно отключаем Liquibase
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: cargo_schema
#    rollback-file: classpath:db/changelog/rollback.sql  # файл для SQL отката

  data:
    mongodb:
      uri: mongodb://localhost:27017/cargo_storage_db

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/logistics
#          jwk-set-uri: http://localhost:8080/realms/logistics/protocol/openid-connect/certs

logging:
  level:
    com.innowise.logistics.platform.user: DEBUG
    liquibase: INFO
