# Для встроенного HTTP-клиента IntelliJ IDEA
@host = http://localhost:8085
@base_path = /api/v1/catalog/reservations

### 1. Создать бронирование (резервирование) товаров по SKU
POST {{host}}{{base_path}}
Content-Type: application/json

[
  {
    "skuId": 1,
    "quantity": 2
  },
  {
    "skuId": 2,
    "quantity": 1
  }
]

### 2. Просмотреть список всех существующих резервирований в системе (Пагинация)
GET {{host}}{{base_path}}?page=0&size=10
Accept: application/json

### 3. Перевести забронированные товары в статус отгрузки (SHIPPED)
PATCH {{host}}{{base_path}}/1/ship
Accept: application/json

### 4. Снять резервирование с товаров (Возврат в AVAILABLE)
PATCH {{host}}{{base_path}}/2/cancel
Accept: application/json


### ❌ ОШИБКА ВАЛИДАЦИИ: Пустой список при создании брони (Trigger @NotEmpty)
POST {{host}}{{base_path}}
Content-Type: application/json

[]

### ❌ ОШИБКА ВАЛИДАЦИИ: Нулевое или отрицательное количество товара (Trigger @Min/@Positive на DTO)
POST {{host}}{{base_path}}
Content-Type: application/json

[
  {
    "skuId": 1,
    "quantity": 0
  }
]

### ❌ ОШИБКА ВАЛИДАЦИИ: Передан null вместо объекта запроса (Trigger List<@NotNull>)
POST {{host}}{{base_path}}
Content-Type: application/json

[
  null
]


### 1. Создать бронирование (резервирование) товаров по SKU
POST {{host}}{{base_path}}
Content-Type: application/json

[
  {
    "skuId": 1,
    "quantity": 2
  },
  {
    "skuId": 2,
    "quantity": 1
  }
]