# Для встроенного HTTP-клиента в IDE

### Получить первую страницу (20 элементов по умолчанию)
GET http://localhost:8085/api/v1/catalog/items

### Получить вторую страницу с размером в 3 элементов (индексация с 0)
GET http://localhost:8085/api/v1/catalog/items?page=2&size=3

### Отсортировать по цене (по возрастанию)
GET http://localhost:8085/api/v1/catalog/items?page=0&size=2000&sort=price,asc

### Отсортировать по дате создания (свежие сверху)
GET http://localhost:8085/api/v1/catalog/items?sort=createdAt,desc



### Получить конкретный товар по его ID (например, ID = 500)
GET http://localhost:8085/api/v1/catalog/items/500

### Проверить обработку ошибки 404 (запрос несуществующего ID, например 9999)
GET http://localhost:8085/api/v1/catalog/items/9999




### Получить первую страницу УНИКАЛЬНЫХ товаров по АРТИКУЛАМ (20 sku по умолчанию)
GET http://localhost:8085/api/v1/catalog/skus

### Получить вторую страницу УНИКАЛЬНЫХ товаров по АРТИКУЛАМ с размером в 3 элементов (индексация с 0)
GET http://localhost:8085/api/v1/catalog/skus?page=2&size=3



### Все доступные товары по конкретному SKU
GET http://localhost:8085/api/v1/catalog/skus/2/items

### Все доступные товары по конкретному SKU с размером в 3 элементов (индексация с 0)
GET http://localhost:8085/api/v1/catalog/skus/2/items?page=2&size=3


