### Для встроенного HTTP-клиента в IDE

### Получить первую страницу (20 элементов по умолчанию)
GET http://localhost:8085/api/v1/catalog/items

### Получить вторую страницу с размером в 10 элементов (индексация с 0)
GET http://localhost:8085/api/v1/catalog/items?page=1&size=10

### Отсортировать по цене (по возрастанию)
GET http://localhost:8085/api/v1/catalog/items?page=0&size=20&sort=price,asc

### Отсортировать по дате создания (свежие сверху)
GET http://localhost:8085/api/v1/catalog/items?sort=createdAt,desc


